
ALTER TABLE public.business_config
  ADD COLUMN IF NOT EXISTS assistant_position TEXT DEFAULT 'right',
  ADD COLUMN IF NOT EXISTS splash_image_url TEXT,
  ADD COLUMN IF NOT EXISTS splash_bg_type TEXT DEFAULT 'solid',
  ADD COLUMN IF NOT EXISTS splash_bg_color TEXT DEFAULT '#0F172A',
  ADD COLUMN IF NOT EXISTS splash_bg_gradient_from TEXT DEFAULT '#7c3aed',
  ADD COLUMN IF NOT EXISTS splash_bg_gradient_to TEXT DEFAULT '#06b6d4',
  ADD COLUMN IF NOT EXISTS splash_duration_ms INTEGER DEFAULT 2000,
  ADD COLUMN IF NOT EXISTS splash_animation BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS splash_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS chat_wallpaper_url TEXT,
  ADD COLUMN IF NOT EXISTS chat_wallpaper_opacity INTEGER DEFAULT 100,
  ADD COLUMN IF NOT EXISTS chat_wallpaper_blur TEXT DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS chat_wallpaper_dim BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS chat_wallpaper_fit TEXT DEFAULT 'cover',
  ADD COLUMN IF NOT EXISTS chat_header_color TEXT DEFAULT '#0b141a',
  ADD COLUMN IF NOT EXISTS chat_input_bg_color TEXT DEFAULT '#1f2c33',
  ADD COLUMN IF NOT EXISTS chat_send_button_color TEXT DEFAULT '#7c3aed',
  ADD COLUMN IF NOT EXISTS chat_ania_bubble_color TEXT DEFAULT '#ffffff',
  ADD COLUMN IF NOT EXISTS chat_user_bubble_color TEXT DEFAULT '#005c4b',
  ADD COLUMN IF NOT EXISTS chat_link_color TEXT DEFAULT '#53bdeb',
  ADD COLUMN IF NOT EXISTS chat_icon_color TEXT DEFAULT '#8696a0',
  ADD COLUMN IF NOT EXISTS chat_catalog_card_color TEXT DEFAULT '#111b21';
